### ISSUE TITLE
Snapshot requires that the page URL must be HTTP or HTTPS

### ISSUE THREAD

**Issue by angellindo** [percy/percy-puppeteer#63]
Hi im having an issue were percy service, it throws an error if I try to snapshot a URL that is a file I opened from the system.

The currently flow is:
1. user client sends an HTML to the backend
2. backend parses the HTML and get what ever data it needs
3. generates a new HTML
4. puppeteer sends back a PDF

I had to do a work around this simple scenario and create a ExpressJS server to provide that generated HTML as `http://localhost/...`

My code looks like

``` JS
  const filePath = resolve(fileName);

  await page.goto(`file://${filePath}`, {
    waitUntil: "networkidle0"
  });
```

but when I run my tests/snapshot on that code I get 
![Screen Shot 2019-03-18 at 2 25 04 PM](https://user-images.githubusercontent.com/1717226/54558824-a68cb880-498c-11e9-9ae9-6c11bdde3e62.png)

Is there a way to handle this?

**Comment by fotinakis** [comment]
Hey @angellindo — thanks for the report. `file://` paths are not supported as a security measure in percy's backend, but could potentially be supported in percy-agent's capturing at some point.

The workaround you found using an express server for this is good and will create better automatic snapshot names anyway, so that's what we would suggest you do here. Going to close this as wontfix since there is a good workaround.
